### ISSUE TITLE
Wifi failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by vearutop** [asymingt/rts5139#1]
I applied this driver on Ubuntu 15.10 and it worked perfectly. But after I updated my system to Ubuntu 16.04 SD reader disappeared again (wifi was working ok). I followed instructions again and installed this driver. SD reader appeared and worked fine, but wifi was unable to find any networks.

Please help to fix :)

**Comment by vearutop** [comment]
Laptop is Lenovo Yoga 13

**Comment by asymingt** [comment]
Hi Viacheslav

Have you tried following the instructions to install drivers here:
https://github.com/lwfinger/rtl8723au
https://github.com/lwfinger/rtl8723au_bt

My yoga 13 seems to work nicely with 16.04. Not sure why your are having
issues. Maybe try different branches of the repo to see if they work?

Also, keep an eye on this thread:
https://github.com/lwfinger/rtl8723au/issues/57

Cheers
Andrew

**Comment by vearutop** [comment]
Hello, thanks for quick reply! 
Indeed https://github.com/lwfinger/rtl8723au/issues/57 is relevant, after I spent some time in windows with Wifi enabled I rebooted back to ubuntu. At this time both Wifi and SD reader were working fine. I did reboot ubuntu again and witnessed Wifi failure.

I tried to install https://github.com/lwfinger/rtl8723au.git (master) but failed at last step

```
$ sudo modprobe 8723au 
modprobe: ERROR: could not insert '8723au': Device or resource busy
```

I suspect this unstable wifi can be related to low battery level, will check further.
Also once I had Wifi working after going to sleep and back. 

Thanks for links!

Best regards

**Comment by asymingt** [comment]
Try typing...

sudo depmod -a

… before you run the mod probe command.

**Comment by damianfanaro** [comment]
Hi,

In my case, the work around was to unload and load again the 'rtl8xxxu' module after every reboot.

Here is the command:

**`sudo rmmod rtl8xxxu && sudo modprobe rtl8xxxu`**

I'm running Linux Mint 18 (Sarah) - Kernel 4.4.0-21-generic.
Laptop: Lonovo Yoga 13

On previous Kernel versions I had to install the driver (rtl8723au) manually.

I hope this issue to be fixed on future Kernel releases.

**Comment by buaazqk** [comment]
I have solved this problem, you can follow the instructions:
1. type  the comment :  lsmod , you can see there is a driver like 'r8723au' already exist.
2. type  the comment:  sudo rmmod r8723au 
3. reinstall the 8723au again, follows: https://github.com/lwfinger/rtl8723au
4. enjoy it.
